# pytest.ini

[pytest]
### Configure where code can be imported from
## Make things importable from the current directory.
## Usually set to "src" with the src-layout.
## For the exercises, we want to do "import rpncalc"
## in all tests without a separate folder.
pythonpath = .


### Plugin disables
# We disable pytest-recording (mocking chapter) and pytest-asyncio (plugin tour),
# as they run various fixtures automatically (autouse=True), which interferes
# with exercises.
# exercise: [marks]
addopts = -p no:recording -p no:asyncio

### For marking/
markers =
    slow: Tests which take some time to run
    webtest: Tests making web requests
    long_prompt: Given test should get a rpn_config with a long prompt
    # exercise: [marks]


### To avoid collecting things from tox/
norecursedirs = .* venv tox
